server:
  port: 19103
spring:
  application:
    name: testDisciplinaryCalculator
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true