server:
  port: 19003
spring:
  application:
    name: reducerDisciplinaryCalculator2
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true